### ISSUE TITLE
Q: what is the transaction id format

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-spec#13]
is it different than MVP?
will it encapsulate more data in it? (see: https://instagram-engineering.com/sharding-ids-at-instagram-1cf5a71e5a5c for inspiration)

**Comment by avilanthe1** [comment]
It's a good idea to encapsulate data in the key/id of transactions.
I'll just mention that, unlike Instagram, you can't a priori know transaction timestamp since it should be relatively to its order compare to any other transaction. Since this order is only determined after the consensus and transaction id should be determined before - it is not possible.

Another thing to remember is that transactions should be encrypted thus there is not a lot of data to be encapsulated in the id.

**Comment by talkol** [comment]
The TxId format is (will be) described in the protos (protobufs definitions).

It will be made from the hash + timestamp and it can be calculated from the transaction data only without sending it.
