### ISSUE TITLE
Node instance names/addresses 

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-spec#15]
A node instance has two meaningful identifications: it's (logical) network address, and the federation member it operates on behalf of.

The node is defined in the spec as "an entity in the network", and also as "sharing a single private key". and "a node is a trust boundary". 

We anticipate nodes to scale out (horizontally) behind a single network address, meaning, under a single node deployment. But a federation member may also like to scale out ״hori-horizontally״ by installing multiple node instances (for different reasons), possibly on different data centres. 

Each such deployment will have a separate Tx Pool, committee seats, block height and reputation scores, so it would make sense to give **each a different private key**,
But on the other hand, they share loyalty and trust with a known federation member, so it makes sense to give them **the same private key**.

It makes sense to postpone dealing with complex scaling scenarios for now, but just as we put in place protobuf interfaces today to anticipate scaling out, maybe we can add a node's instance name next to each public key mention? this way we avoid the ambiguity of node addressing.

**Comment by talkol** [comment]
Good points.

The requirements of V1 don't deal with this use case yet. Every federation member will run a single node and all machines under it are their own concern (usually active standby - from the rest of the network perspective they appear as one).

We're pushing this concern to future versions. We don't want to prepare protocol fields in advance because we don't have enough evidence to back up their format. The protocol is designed to evolve.
