### ISSUE TITLE
Transaction pool: same content for GetTransactionsForOrdering and Validate

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-spec#16]
in txpool there may be a copy paste issue, and its really unclear
GetTransactionsForOrdering
and
ValidateTransactionsForOrdering
have the same content, clarify?

**Comment by talkol** [comment]
There's no mistake there, from a spec perspective they're very similar but not identical. The developer can extract functions of common logic, the spec does not attempt to extract or do "code" reuse

**Comment by jlevison** [comment]
so the issue is different, five different people looked at it and found it confusing, maybe its a flow issue, how are they to be used / called by (do not answer here, just add a reference in the spec on each of them)

**Comment by talkol** [comment]
It's two different but very similar actions.

`GetTransactionsForOrdering` - called by the leader when the leader is supposed to propose a block, this function chooses which transactions will go into the proposed block

`ValidateTransactionsForOrdering` - called by all the validators after the leader proposes a block, this function goes over what the leader proposes and makes sure it's legit

They indeed have very similar logic because one validates the actions of the other, but if you look closely you will see that they are not identical.

It looks like a mistake because you were suspicious of copy paste with slight modifications, but it isn't a copy paste mistake, just identical logic for the most part.
